meta_name: "Yann Lecocq"
meta_title: "Hypnose Ericksonienne - Nantes"
meta_description: "Gestion des émotions, peurs, phobies, stress, arrêt du tabac, Hypnose Régressive, Sommeil, Anxiété, Confiance en Soi, Estime de Soi, Deuil"
meta_image: "YannLecocq-Hypnose44.png" alt= "Yann Lecocq Hypnose Ericksonienne Nantes# should exist in `app/assets/images/`
instagram_account: "@yannlecocqhypnose44"
facebook_account: "@yannlecocqhypnose44"
